<?php

/**
* Implements hook_rules_action_info
*/
function date_ical_rules_rules_action_info() {
  return array(
    'generate_date_ical_file' => array(
      'label' => t('Generate iCal File'),
      'group' => t('Date iCal'),
      'parameter' => array(
        'url' => array(
          'label' => t('iCal Feed URL'),
          'type' => 'text',
          'description' => t('Enter the url for the iCal feed this will be used to generate the file.')
        ),
        'filename' => array(
          'label' =>t('Filename'),
          'type' => 'text',
          'description' => t('Enter the filename to use for the iCal file. Do not include the file extension.')
        )
      ),
      'provides' => array(
        'file' => array(
          'type' => 'entity',
          'label' => t('File')
        ),
        'filepath' => array(
          'type' => 'text',
          'label' => t('Filepath')
        )
      )
    ),
  );
}

/**
* Callback function to generate the ical file.
*/
function generate_date_ical_file($url, $filename = '') {

  $content = file_get_contents('http://' .$_SERVER['HTTP_HOST'] . $url);
  if ($file = file_save_data($content, 'public://' . $filename .'.ics' ) ) {
    $relative_path = file_create_url($file->uri);
    $relative_path = str_replace('http://' .$_SERVER['HTTP_HOST']. '/' , '', $relative_path);
    return array(
      'file' => $file,
      'filepath' => $relative_path
    );
  }
  else {
    drupal_set_message(t('Could not create file.'));
    return array(
      'file' => NULL,
      'filepath' => NULL
    );
  }

}

?>
